name: Publish Docker image

on:
  push:
    branches: master
  pull_request:
    branches: master

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'npm'
        - run: npm ci
        - run: npm run build --if-present
        - run: npm test

      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.TOKEN }}

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and push Docker image (rails api server)
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./base-api-server/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/node_docker_git_actions:latest
