name: Publish Docker image
# workflow가 trigger될 이벤트를 명시한다. push하면 실행!
on:
  push:
    branches: master
  pull_request:
    branches: master
# workflow에서 실행할 job
jobs:
  build-and-push-image:
    # job이 돌아갈 환경을 명시한다.
    runs-on: ubuntu-latest
    # permissions:
    #   contents: read
    #   packages: write
    # 하나의 job에서 실행할 step 명시한다.
    steps:
      - name: Checkout repository
        # uses는 다른 오픈소스 커뮤니티에 있는 actions를 가지고 와서 실행하라고 job에게 알려준다.
        # checkout@v3는 레파지토리 환경을 runner로 복사한다.
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ghcr.io/${{ secrets.DOCKER_HUB_USERNAME }}/node_docker_git_actions:latest
